import type { Metadata } from "next";
import type { FC, PropsWithChildren } from "react";
import {
	ColorSchemeScript,
	MantineProvider,
	mantineHtmlProps,
} from "@mantine/core";

import FooterMenu from "@/components/nav/FooterMenu/FooterMenu";
import MainMenu from "@/components/nav/MainMenu/MainMenu";

import "@mantine/core/styles.css";
import "@/styles/globals.scss";

// @todo
const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

/**
 * Root Layout Component
 */
const RootLayout: FC<PropsWithChildren> = ({ children }) => {
	return (
		<html lang="en" {...mantineHtmlProps}>
			<head>
				<ColorSchemeScript />
			</head>

			<body>
				<MantineProvider defaultColorScheme="dark">
					<header>
						<MainMenu />
					</header>

					<main>{children}</main>

					<footer>
						<FooterMenu />
						<div className="copyright">Copyright © Always Obsolete 2025</div>
					</footer>
				</MantineProvider>
			</body>
		</html>
	);
};

export { metadata };
export default RootLayout;
