import type { Metadata } from "next";
import type { FC, PropsWithChildren } from "react";
import {
	ColorSchemeScript,
	MantineProvider,
	mantineHtmlProps,
} from "@mantine/core";

import MainMenu from "@/components/nav/MainMenu/MainMenu";

import "@mantine/core/styles.css";
import "@/styles/globals.scss";

// @todo
const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

/**
 * Root Layout Component
 */
const RootLayout: FC<PropsWithChildren> = ({ children }) => {
	return (
		<html lang="en" {...mantineHtmlProps}>
			<head>
				<ColorSchemeScript />
			</head>

			<body>
				<MantineProvider defaultColorScheme="dark">
					<MainMenu />

					{children}
				</MantineProvider>
			</body>
		</html>
	);
};

export { metadata };
export default RootLayout;
